# Generated by Django 3.2.5 on 2022-02-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderadvertising',
            name='isLive',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
