# Generated by Django 3.2.5 on 2022-03-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_orderadvertising_islive'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderadvertising',
            name='url',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
