# Generated by Django 3.2.5 on 2022-02-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consulting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconsulting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
