# Generated by Django 3.2.5 on 2022-03-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consulting', '0002_orderconsulting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsulting',
            name='consulting_time',
            field=models.CharField(blank=True, default='در حال برسی', max_length=255, null=True),
        ),
    ]
