# Generated by Django 3.2.5 on 2022-03-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consulting', '0003_alter_orderconsulting_consulting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconsulting',
            name='url',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
